version: '1'
services:
  model-gen-api:
    build:
      context: .devcontainer/api
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    networks:
      - mynetwork

  model-gen-frontend:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    networks:
      - mynetwork

networks:
  mynetwork: